### ISSUE TITLE
Skillnamen auswählen

### ISSUE THREAD

**Issue by kgruenwa** [ID-Start-Winter21/Team_05#21]

**Comment by VladP27** [comment]
- AlexaJr
- Alexa Kids
- Playlexa
- Magic Alexa
- Learn with Alexa
- Spaß mit Alexa
- Palexa (pal + alexa)
- Young Alexa
- Kidsa 
- Alexi
- AlexaFun
- AlexaPlay
- Farmlexa
- Alexa's Farm
- Kids Farm
- Kinder Farm
- Spaß Farm
- FunFarm
- Alexa's kunterbunte Farm

**Comment by kgruenwa** [comment]
Endgültiger Name: Kids Farm
