### ISSUE TITLE
Audio Problem auf Alexa Developer Console 

### ISSUE THREAD

**Issue by mrtkfl** [ID-Start-Winter21/Team_05#31]

**Comment by kgruenwa** [comment]
Habe Probe skill erstellt und probiere damit momentan die Audio hinzufügten.

**Comment by kgruenwa** [comment]
Audio wurden hinzugefügt:
Das Problem war das ich diese zunächst nicht öffentlich für alle zugänglich gemacht habe. Somit ging der Link der ich eingefügt habe nicht. Mit der Unterstützung auch Gruppe 07 und Michael sind wir auf das Problem gekommen. Außerdem mussten die Audios auf 22050 Herz gebracht werden da Alexa höhere Herzraten nicht ausgibt.

Zusammenfassung : Alle Audios sind drin. Mert und ich haben dies in Patnerarbeit gemeinsam erledigt.

**Comment by mrtkfl** [comment]
Alle Audios sind auf S3 und funktionieren auf Alexa Developer Console.
