### ISSUE TITLE
Audio Implimentiren

### ISSUE THREAD

**Issue by Gipliz** [ID-Start-Winter21/Team_05#32]

**Comment by kgruenwa** [comment]
Audios befinden sich momentan schon in der s3 storage (aws)

**Comment by kgruenwa** [comment]
Audio wurden in den Code eingefügt. Der code um ein Audio einzufügen lautet:
**speak_output = '<audio src="https://audiokidsskillfarm.s3.eu-west-1.amazonaws.com/huhn2.mp3"/>'**

(Um ein neues Audio einzufügen muss nur die https Adresse ausgetauscht werden) 
[Code kann man leider nur vollständig erkennen sobald man auf Edit klickt da die Anführungszeichen den Code ausklammern]

**Comment by mrtkfl** [comment]
Audios implementiert auf Alexa developer console.
