### ISSUE TITLE
Hi!A Festival

### ISSUE THREAD

**Issue by VladP27** [ID-Start-Winter21/Team_05#33]
Wie passt unsere Idee zum Hi!A Festival -> in die Wiki/ReadMe

**Comment by kgruenwa** [comment]
Der Farmskill soll die noch unausgeschöpften Anwendungsmöglichkeiten von Kinderspielen mit der Hilfe von sprachgesteuerten Systemen präsentieren.
Mittels Audio und einer sich natürlich anfühlenden Dialogstruktur führen wir durch eine interaktive Geschichte, bei der es sich um eine Führung von Bauer Herrmann über seinen Hof handelt. Um eine Bessere Userexperience zu generieren benutzen wir zusätzlich zu der Alexa, die Aws Deep Lens Kamera .

**Comment by kgruenwa** [comment]
jetzt muss ich noch ein bisschen zu der Hi!A referieren dann können Marco und ich weiterschreiben.
