### ISSUE TITLE
Dummy-Server mit Alexa verbinden

### ISSUE THREAD

**Issue by michaeleggers** [ID-Start-Winter21/Team_05#37]
Ich habe, wie besprochen, einen dummy server hinzugefuegt. Bitte mal ausprobieren, so wie am Freitag besprochen. Wenn ihr nicht weiterkommt, gebt mir Bescheid :)

**Comment by kgruenwa** [comment]
Ich habe den Dummy-server hinzugefügt in einen intent bisher
