### ISSUE TITLE
Auftreten beim Hi!A Festival

### ISSUE THREAD

**Issue by VladP27** [ID-Start-Winter21/Team_05#41]
Unser Auftreten als Team muss für das Festival geplant werden. 

- Präsentation
- Vorführung des Skills
- Interaktion zwischen Zuschauer und Skill?

**Comment by VladP27** [comment]
https://github.com/ID-Start-Winter21/Team_05/wiki/Sprint-2

**Comment by kgruenwa** [comment]
Alles über H!iA steht im Wiki
