### ISSUE TITLE
Alexa und Kamera Verbinden

### ISSUE THREAD

**Issue by mrtkfl** [ID-Start-Winter21/Team_05#7]

**Comment by mrtkfl** [comment]
Wie verbinden wir Alexa und kamera. Ist es überhaupt möglich?

**Comment by kgruenwa** [comment]
AWS anmelden 

Websites mit infos:
https://aws.amazon.com/blogs/machine-learning/use-aws-deeplens-to-give-amazon-alexa-the-power-to-detect-objects-via-alexa-skills/
https://aws.amazon.com/blogs/machine-learning/building-a-pictionary-style-game-with-aws-deeplens-and-amazon-alexa/

**Comment by mrtkfl** [comment]
AWS angemeldet

**Comment by mrtkfl** [comment]
AWS deeplens kann nicht registriert werden.
